name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: read JSON property
      id: read_property
      uses: notiz-dev/github-action-json-property@release
      with:
        # path to json file
        path: ./GlucoseTraycore/appsettings.json
        # which property to read
        prop_path: appsettings.Version
    - name: Create a Release
      uses: softprops/action-gh-release@v0.1.5
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with: 
        files: |
          ./GlucoseTrayCore\bin\Release\netcoreapp3.1\win-x64\publish\appsettings.json
          ./GlucoseTrayCore\bin\Release\netcoreapp3.1\win-x64\publish\GlucoseTrayCore.exe
        name: 'Glucose Tray - ${{steps.read_property.outputs.prop}}'
        tag_name: ${{steps.read_property.outputs.prop}}
        draft: false
        prerelease: false
