name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: read JSON property
      uses: ashley-taylor/read-json-property-action@v1.0
      with:
        # path to json file
        path: ./GlucoseTraycore/
        # json input
        json: appsettings.json
        # which property to read
        property: Version
        outputs: AppVersion
    - name: Publish Release
      uses: eregon/publish-release@v1.0.3
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The ID of the draft release to publish
        release_id: ${{ steps.read_property.outputs.value }}
